# Generated by Django 4.0.5 on 2023-05-28 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.table'),
        ),
    ]
