# Generated by Django 4.0.5 on 2023-05-28 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_task_task_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.table'),
        ),
    ]
