# Generated by Django 4.0.5 on 2023-06-01 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='subgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.group'),
        ),
    ]
