# Generated by Django 4.0.5 on 2023-06-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_group_subgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_subgroup',
            field=models.BooleanField(default=False),
        ),
    ]
