# Generated by Django 4.0.5 on 2023-06-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_group_has_subgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='subgroup',
        ),
        migrations.AddField(
            model_name='group',
            name='subgroup',
            field=models.ManyToManyField(null=True, to='base.group'),
        ),
    ]
