# Generated by Django 4.0.5 on 2023-06-02 00:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0010_remove_group_subgroup_group_subgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='table',
            name='TableGroup',
            field=models.ManyToManyField(to='base.group'),
        ),
    ]
